name: ci-test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-verison: ^1.15
          id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@2

      - name: Test
        run: make test
